CU-#2nfp7pm - FRONTEND: Сделать компонент чекбокса
dmitryduy/work-fly pull request #21
Opened 2022-07-02 10:36 UTC by edword03

https://app.clickup.com/t/2nfp7pm

2022-07-02 10:36 UTC, dmitryduy commented
Task linked: [CU-2nfp7pm FRONTEND: Сделать компонент чекбокса](https://app.clickup.com/t/2nfp7pm)

2022-07-03 09:47 UTC, whicencer requested changes

2022-07-03 10:05 UTC, dmitryduy commented on frontend/src/ui/CheckBox/CheckBox.interface.ts
> +  toggleCheckbox?: () => void
> Сделай тип для toggleCheckbox `Dispatch<SetStateAction<тип_который_должен_приходить>>`

Не забывай, что у нас будет react hook form.

2022-07-03 10:07 UTC, whicencer commented on frontend/src/ui/CheckBox/CheckBox.interface.ts
> +  toggleCheckbox?: () => void
> > Сделай тип для toggleCheckbox `Dispatch<SetStateAction<тип_который_должен_приходить>>`
> 
> Не забывай, что у нас будет react hook form.

и что? тогда скажи как сделать апрув?

2022-07-03 10:08 UTC, dmitryduy commented on frontend/src/ui/CheckBox/CheckBox.interface.ts
> +  toggleCheckbox?: () => void
> > > Сделай тип для toggleCheckbox `Dispatch<SetStateAction<тип_который_должен_приходить>>`
> > 
> > 
> > Не забывай, что у нас будет react hook form.
> 
> и что? тогда скажи как сделать апрув?

Он по другому типизирован

2022-07-03 10:08 UTC, whicencer approved these changes
ок. объедини коммиты через rebase

2022-07-06 15:56 UTC, dmitryduy commented on frontend/src/ui/CheckBox/CheckBox.styles.ts
> +      left: 12.5px;
Странный сдвиг. Тут точно нужны дробные части?

2022-07-06 16:50 UTC, merged