CU-2nfp7m4 - FRONTEND: Сделать компонент тегов
dmitryduy/work-fly pull request #22
Opened 2022-07-02 20:25 UTC by n1qcode

- сделан компонент Tag
- сделан компонент Label
- пофиксил children type у StyleProvider.tsx

2022-07-02 20:25 UTC, dmitryduy commented
Task linked: [CU-2nfp7m4 FRONTEND: Сделать компонент тегов](https://app.clickup.com/t/2nfp7m4)

2022-07-02 20:40 UTC, dmitryduy commented on frontend/src/ui/Label/Label.styles/index.ts
> +  flex-direction: row;
Это бесполезная строчка. По умолчанию и так идёт row

2022-07-02 20:40 UTC, dmitryduy commented on frontend/src/ui/Label/Label.styles/index.ts
> +  font-size: 15px;
Шрифты есть в теме

2022-07-02 20:40 UTC, dmitryduy commented on frontend/src/ui/Label/Label.styles/index.ts
> +  background-color: #EBEBEB;
Цвета есть в теме(если его нет, то напиши коммент об этом)

2022-07-02 20:40 UTC, dmitryduy commented on frontend/src/ui/Label/Label.styles/index.ts
> +  color: #030235;
Тоже самое, что сверху

2022-07-02 20:40 UTC, dmitryduy commented on frontend/src/ui/Label/Label.styles/index.ts
> +  border-radius: 100px;
Не понятно для чего такой большой радиус

2022-07-02 20:40 UTC, dmitryduy commented on frontend/src/ui/Label/Label.typings/index.ts
> +  fn: () => void;
Получши придумай название для функции

2022-07-02 20:40 UTC, dmitryduy commented on frontend/src/ui/Tag/Tag.styles/index.ts
> +  flex-direction: row;
Row по дефолту

2022-07-02 20:40 UTC, dmitryduy commented on frontend/src/ui/Tag/Tag.styles/index.ts
> +  font-size: 15px;
Шрифты есть в теме

2022-07-02 20:40 UTC, dmitryduy commented on frontend/src/ui/Tag/Tag.styles/index.ts
> +  border-radius: 100px;
Откуда такой большой радиус

2022-07-02 20:40 UTC, dmitryduy commented on frontend/src/ui/Tag/Tag.styles/index.ts
> +  height: 24px;
Не вижу смысла делать фиксированную высоту. Убери вообще её. Пусть будут только padding

2022-07-02 20:40 UTC, dmitryduy commented on frontend/src/ui/Label/Label.styles/index.ts
> +  padding: 4px 8px;
Не вижу смысла делать фиксированную высоту. Убери вообще её. Пусть будут только padding

2022-07-02 20:40 UTC, dmitryduy commented on frontend/src/ui/Tag/Tag.typings/index.ts
> +  backColor: string;
Переиминуй в backgoundColor

2022-07-02 20:40 UTC, dmitryduy commented on frontend/src/ui/Tag/Tag.typings/index.ts
> +  backColor: string;
Переименуй в backgroundColor

2022-07-02 20:57 UTC, n1qcode commented on frontend/src/ui/Label/Label.styles/index.ts
> +  flex-direction: row;
убрал

2022-07-02 20:57 UTC, n1qcode commented on frontend/src/ui/Label/Label.styles/index.ts
> +  font-size: 15px;
убрал

2022-07-02 20:57 UTC, n1qcode commented on frontend/src/ui/Label/Label.styles/index.ts
> +  color: #030235;
+

2022-07-02 20:57 UTC, n1qcode commented on frontend/src/ui/Label/Label.styles/index.ts
> +  border-radius: 100px;
было в макете, уменьшил до 15px

2022-07-02 20:58 UTC, n1qcode commented on frontend/src/ui/Tag/Tag.styles/index.ts
> +  border-radius: 100px;
было в макете, уменьшил до 15px

2022-07-02 20:58 UTC, n1qcode commented on frontend/src/ui/Tag/Tag.styles/index.ts
> +  height: 24px;
убрал

2022-07-02 20:58 UTC, n1qcode commented on frontend/src/ui/Label/Label.styles/index.ts
> +  padding: 4px 8px;
убрал

2022-07-02 20:58 UTC, n1qcode commented on frontend/src/ui/Tag/Tag.typings/index.ts
> +  backColor: string;
сделано

2022-07-02 20:58 UTC, n1qcode commented on frontend/src/ui/Tag/Tag.typings/index.ts
> +  backColor: string;
сделано

2022-07-02 20:58 UTC, n1qcode commented on frontend/src/ui/Tag/Tag.styles/index.ts
> +  font-size: 15px;
сделано

2022-07-02 20:59 UTC, n1qcode commented on frontend/src/ui/Tag/Tag.styles/index.ts
> +  flex-direction: row;
поправил

2022-07-02 21:04 UTC, n1qcode commented on frontend/src/ui/Label/Label.typings/index.ts
> +  fn: () => void;
сделал labelLogicFunc

2022-07-03 09:47 UTC, whicencer requested changes

2022-07-03 09:47 UTC, whicencer commented on frontend/src/providers/StyleProvider.typings/index.ts
> +export interface IStyleProvider {
IStyleProviderProps. это интерфейс для пропсов

2022-07-03 09:47 UTC, whicencer commented on frontend/src/providers/StyleProvider.tsx
> -const StyleProvider: FC = ({ children }) => {
Я думаю что это надо было фиксить в другой ветке

2022-07-03 10:39 UTC, edword03 commented on frontend/src/ui/Label/index.tsx
> +      {labelIcon &&
тут лучше сделать более гибко, ибо иконки явно будут меняться, поэтому их лучше как пропс прокидывать сюда, но с иконками мы пока не решили ничего, поэтому пусть пока так будет

2022-07-03 11:05 UTC, n1qcode commented on frontend/src/ui/Label/index.tsx
> +      {labelIcon &&
я увидел в макете только два типа иконок, поэтому сделал так

2022-07-03 11:15 UTC, n1qcode commented on frontend/src/providers/StyleProvider.typings/index.ts
> +export interface IStyleProvider {
поправил

2022-07-03 11:15 UTC, n1qcode commented on frontend/src/providers/StyleProvider.tsx
> -const StyleProvider: FC = ({ children }) => {
мне кажется эти правки слишком незначительны чтобы выносить в отдельную ветку, впрочем мне без разницы

2022-07-03 19:32 UTC, edword03 approved these changes

2022-07-03 19:33 UTC, edword03 approved these changes

2022-07-08 18:00 UTC, n1qcode commented on frontend/src/ui/Label/Label.styles/index.ts
> +  display: inline-flex;
если просто flex, то он будет растягиваться во всю ширину родителя

2022-07-13 16:33 UTC, dmitryduy approved these changes

2022-07-13 16:33 UTC, merged